# примеры API-запросов

@baseUrl = http://localhost:8000/api

# получение объявлений
GET {{baseUrl}}/advertisements/
Content-Type: application/json

###

# создание объявления
POST {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token 7b700961ab5242efb64cb29af167b6022bddff3a

{
  "title": "Шкаф IKEA",
  "description": "Срочно"
}

###
DELETE {{baseUrl}}/advertisements/24/
Authorization: Token b3c7b071114b6df08ed28638e185566c47bba7d9

###

# попытка поменять объявление
PATCH {{baseUrl}}/advertisements/24/
Content-Type: application/json
Authorization: Token 7b700961ab5242efb64cb29af167b6022bddff3a

{
  "status": "CLOSED"
}

###

# фильтрация по (создателя заменил на статус по заданию) 
GET {{baseUrl}}/advertisements/?status=OPEN
Content-Type: application/json

###

# фильтрация по дате
GET {{baseUrl}}/advertisements/?created_at_before=2025-08-17 
Content-Type: application/json
