# Generated by Django 5.2.3 on 2025-07-24 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_remove_student_teacher_alter_student_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentsteacher',
            name='qty',
        ),
    ]
